// Canonical demo briefing. Used by the ?demo=seed URL param for offline
// rehearsal and as a last-resort fallback if both the API and localStorage
// cache fail. Hand-written to match the narrative of public/sample-data.csv.

export const DEMO_BRIEFING = {
  week_label: 'Week 24, June 10–16, 2026',
  summary: {
    en: 'Sell-through is up 5% week-over-week, but the story is bifurcated: Medellín is the strongest market with double-digit growth across eight accounts, while Bogotá is flat and Cali is contracting. Antioqueño has taken prime shelf space in two high-volume Bogotá stores and we are burning over 4 million COP in promo spend on three accounts that are losing bottles.',
    es: 'Las ventas subieron 5% semana contra semana, pero la historia está dividida: Medellín es el mercado más fuerte con crecimiento de dos dígitos en ocho cuentas, mientras que Bogotá está plana y Cali se contrae. Antioqueño se apoderó de la góndola principal en dos tiendas de alto volumen en Bogotá y estamos quemando más de 4 millones de COP en promoción en tres cuentas que pierden botellas.',
  },
  top_growers: [
    { account: 'Bar La Puerta Falsa', region: 'Bogotá', wow_pct: 39, bottles_delta: 25 },
    { account: 'Éxito Chapinero', region: 'Bogotá', wow_pct: 32, bottles_delta: 45 },
    { account: 'Carulla Poblado', region: 'Medellín', wow_pct: 28, bottles_delta: 39 },
  ],
  bottom_decliners: [
    {
      account: 'Carulla Cedritos',
      region: 'Bogotá',
      wow_pct: -57,
      returns: 2,
      reason_en: 'Antioqueño took our eye-level slot; we were demoted to the bottom shelf and volume halved.',
      reason_es: 'Antioqueño tomó nuestra ubicación a nivel de visión; fuimos relegados a la repisa inferior y el volumen se redujo a la mitad.',
    },
    {
      account: 'Tienda Don Pepe',
      region: 'Bogotá',
      wow_pct: -41,
      returns: 11,
      reason_en: 'Back-counter placement plus eleven returns on only 22 bottles sold, despite 1.8M COP in promo.',
      reason_es: 'Ubicación tras el mostrador con once devoluciones sobre 22 botellas vendidas, a pesar de 1.8M COP en promoción.',
    },
    {
      account: 'Tienda El Paisa Bogotá',
      region: 'Bogotá',
      wow_pct: -38,
      returns: 5,
      reason_en: 'Nariño displaced us to the back counter; the promo budget is buying invisibility.',
      reason_es: 'Nariño nos relegó tras el mostrador; el presupuesto promocional está comprando invisibilidad.',
    },
  ],
  competitor_threats: [
    {
      account: 'Carulla Cedritos',
      was_position: 'Eye-level',
      now_position: 'Bottom Shelf',
      winning_competitor: 'Antioqueño',
      note_en: 'A flagship Bogotá supermarket: volume dropped from 168 to 72 bottles in a single week after the swap.',
      note_es: 'Supermercado emblemático en Bogotá: el volumen cayó de 168 a 72 botellas en una sola semana tras el cambio.',
    },
    {
      account: 'Tienda Don Pepe',
      was_position: 'Bottom Shelf',
      now_position: 'Back Counter',
      winning_competitor: 'Antioqueño',
      note_en: 'Further relegation — now literally out of sight. Customers cannot buy what they cannot see.',
      note_es: 'Relegación adicional — ahora literalmente fuera de vista. El cliente no compra lo que no ve.',
    },
    {
      account: 'Bar La Topa Tolondra',
      was_position: 'Eye-level',
      now_position: 'Top Shelf',
      winning_competitor: 'Blanco del Valle',
      note_en: 'Cali pressure continues: Blanco del Valle displaced us at a flagship salsa bar last Thursday.',
      note_es: 'La presión en Cali no cede: Blanco del Valle nos desplazó en un bar de salsa emblemático el jueves pasado.',
    },
  ],
  promo_inefficiency: [
    {
      account: 'Tienda Don Pepe',
      promo_spend_cop: 1800000,
      bottles_sold: 22,
      waste_ratio: 81818,
      note_en: 'Worst ROI of the week: 82K COP per bottle on an account that is declining 41% WoW.',
      note_es: 'El peor retorno de la semana: 82K COP por botella en una cuenta que cae 41% semanal.',
    },
    {
      account: 'Tienda El Paisa Bogotá',
      promo_spend_cop: 1500000,
      bottles_sold: 18,
      waste_ratio: 83333,
      note_en: '83K COP per bottle on an account that shrunk 38%. Cancel the spend this week.',
      note_es: '83K COP por botella en una cuenta que se contrajo 38%. Cancele el gasto esta semana.',
    },
    {
      account: 'Tienda San Fernando',
      promo_spend_cop: 1100000,
      bottles_sold: 28,
      waste_ratio: 39286,
      note_en: 'A Cali corner store burning 1.1M COP for 28 bottles while the regional market contracts.',
      note_es: 'Tienda de barrio en Cali quemando 1.1M COP por 28 botellas mientras el mercado regional se contrae.',
    },
  ],
  actions: [
    {
      priority: 1,
      title_en: 'Visit Carulla Cedritos personally before Wednesday',
      title_es: 'Visite personalmente Carulla Cedritos antes del miércoles',
      detail_en: 'Reclaim eye-level placement. Losing this spot to Antioqueño cut volume from 168 to 72 bottles in one week. Bring a sample case and the Medellín growth numbers to the category manager — this is a recoverable account if we move fast.',
      detail_es: 'Recupere la ubicación a nivel de visión. Perder este espacio ante Antioqueño cortó el volumen de 168 a 72 botellas en una semana. Lleve una caja de muestra y los números de crecimiento de Medellín al gerente de categoría — es una cuenta recuperable si actuamos rápido.',
    },
    {
      priority: 2,
      title_en: 'Reallocate 4.4M COP of wasted promo to Medellín',
      title_es: 'Reasigne 4.4M COP de promoción desperdiciada a Medellín',
      detail_en: 'Pull spend from Tienda Don Pepe, Tienda El Paisa Bogotá, and Tienda San Fernando. Redirect to Éxito Poblado and Carulla Poblado where 1M COP is already generating 25%+ WoW growth. Same budget, better return.',
      detail_es: 'Retire el gasto de Tienda Don Pepe, Tienda El Paisa Bogotá y Tienda San Fernando. Redirija a Éxito Poblado y Carulla Poblado donde 1M COP ya genera crecimiento superior al 25% semanal. Mismo presupuesto, mejor retorno.',
    },
    {
      priority: 3,
      title_en: 'Lock in eye-level at three Medellín bars before Friday',
      title_es: 'Asegure el nivel de visión en tres bares de Medellín antes del viernes',
      detail_en: 'Bar El Tibirí, Salón Málaga, and Medellín Rock are all growing double digits on minimal promo spend. Sign quarterly visibility agreements now, before Antioqueño or Néctar notice and counter-bid.',
      detail_es: 'Bar El Tibirí, Salón Málaga y Medellín Rock crecen a dos dígitos con mínima promoción. Firme acuerdos trimestrales de visibilidad ahora, antes de que Antioqueño o Néctar se enteren y contra-oferten.',
    },
  ],
  chart_data: [
    { account: 'Bar La Puerta Falsa', wow_pct: 39 },
    { account: 'Éxito Chapinero', wow_pct: 32 },
    { account: 'Carulla Poblado', wow_pct: 28 },
    { account: 'Éxito Poblado', wow_pct: 21 },
    { account: 'Bar El Tibirí', wow_pct: 21 },
    { account: 'Restaurante Hato Viejo', wow_pct: 20 },
    { account: 'Olímpica Cali', wow_pct: 19 },
    { account: 'Bar Salón Málaga', wow_pct: 18 },
    { account: 'Tienda El Paisa Medellín', wow_pct: 18 },
    { account: 'Olímpica Medellín Centro', wow_pct: 17 },
    { account: 'Tienda Don Berna', wow_pct: 17 },
    { account: 'Restaurante El Cielo', wow_pct: 17 },
    { account: 'Tienda La Arenosa', wow_pct: 17 },
    { account: 'Bar Medellín Rock', wow_pct: 15 },
    { account: 'Tienda Getsemaní', wow_pct: 15 },
    { account: 'Restaurante Carmen', wow_pct: 14 },
    { account: 'Carulla Chicó', wow_pct: 13 },
    { account: 'Éxito Barranquilla', wow_pct: 12 },
    { account: 'Restaurante Criterion', wow_pct: 12 },
    { account: 'Bar Café del Mar', wow_pct: 11 },
    { account: 'Olímpica Plaza Central', wow_pct: 10 },
    { account: 'Carulla Castillogrande', wow_pct: 8 },
    { account: 'Bar La Troja', wow_pct: 8 },
    { account: 'Bar Havana Cartagena', wow_pct: 7 },
    { account: 'Restaurante Cucayo', wow_pct: 7 },
    { account: 'Bar Andrés Bogotá', wow_pct: 6 },
    { account: 'Olímpica Buenavista', wow_pct: 6 },
    { account: 'Éxito Usaquén', wow_pct: 5 },
    { account: 'Éxito Bocagrande', wow_pct: 3 },
    { account: 'Bar Frogg', wow_pct: -6 },
    { account: 'Tienda La Esquina', wow_pct: -9 },
    { account: 'Bar Zaperoco', wow_pct: -11 },
    { account: 'Éxito Cali Sur', wow_pct: -13 },
    { account: 'Carulla Cali Norte', wow_pct: -13 },
    { account: 'Restaurante Platillos Voladores', wow_pct: -14 },
    { account: 'Tienda San Fernando', wow_pct: -18 },
    { account: 'Bar La Topa Tolondra', wow_pct: -19 },
    { account: 'Restaurante La Candelaria', wow_pct: -21 },
    { account: 'Tienda El Peñón', wow_pct: -23 },
    { account: 'Tienda El Paisa Bogotá', wow_pct: -38 },
    { account: 'Tienda Don Pepe', wow_pct: -41 },
    { account: 'Carulla Cedritos', wow_pct: -57 },
  ],
};
